// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Text1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Text1, 774);
    lv_obj_set_height(ui_Text1, 211);
    lv_obj_set_x(ui_Text1, -9);
    lv_obj_set_y(ui_Text1, -127);
    lv_obj_set_align(ui_Text1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Text1, "Placeholder...");



    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard2, 689);
    lv_obj_set_height(ui_Keyboard2, 199);
    lv_obj_set_x(ui_Keyboard2, -25);
    lv_obj_set_y(ui_Keyboard2, 132);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_Text2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Text2, 562);
    lv_obj_set_height(ui_Text2, 37);
    lv_obj_set_x(ui_Text2, -106);
    lv_obj_set_y(ui_Text2, 6);
    lv_obj_set_align(ui_Text2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Text2, "Placeholder...");



    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 31);
    lv_obj_set_x(ui_Button2, 341);
    lv_obj_set_y(ui_Button2, 8);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "语音输入");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 31);
    lv_obj_set_x(ui_Button3, 231);
    lv_obj_set_y(ui_Button3, 8);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "发送按键");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_chinese20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
