// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ai_test_v2.h"
#include <string.h>
#include <stdlib.h>

// 语音输入AI回复
static void voice_ai_timer_cb(lv_timer_t *timer)
{
    char *reply = ai_reply();
    if (reply != NULL) {
        lv_textarea_set_text(ui_Text1, reply);    // Textarea 用这个
		printf("AI回复: %s\n", reply);
        free(reply);
    } else {
        lv_textarea_set_text(ui_Text1, "AI回复失败");
    }
    lv_timer_del(timer);
}

// 文本输入AI回复
static void text_ai_timer_cb(lv_timer_t *timer)
{
    char *input = (char *)timer->user_data;
    char *reply = ai_reply_with_text(input);
    if (reply != NULL) {
        lv_textarea_set_text(ui_Text1, reply);
        free(reply);
    } else {
        lv_textarea_set_text(ui_Text1, "AI回复失败");
    }
    free(input);
    lv_timer_del(timer);
}

void on_voice_button_click(lv_event_t * e)
{
    lv_textarea_set_text(ui_Text1, "正在录音识别...");
    lv_timer_create(voice_ai_timer_cb, 100, NULL);
}

void on_send_button_click(lv_event_t * e)
{
    const char *input_text = lv_textarea_get_text(ui_Text2);  // Textarea 用这个
    if (input_text == NULL || strlen(input_text) == 0) {
        lv_textarea_set_text(ui_Text1, "请先输入内容");
        return;
    }
    lv_textarea_set_text(ui_Text1, "正在获取AI回复...");
    char *text_copy = strdup(input_text);
    lv_timer_create(text_ai_timer_cb, 100, text_copy);
}