// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void on_voice_button_click(lv_event_t * e)
{
	// Your code here
}

void on_send_button_click(lv_event_t * e)
{
	// Your code here
}
